### PR TITLE
Added translation settings and added french language

### PR DESCRIPTION
**Pull request by LOUDO56**
I think it's better to have more language available :)

### CODE REVIEW

**Comment by MegaPiggy** [comment]
Thanks

**Comment by LOUDO56** [comment]
Hi, I don't know what happened but the default config is empty, while I've added the two languages. We can't change the language trough the game.

**Comment by MegaPiggy** [comment]
I made it use the language you have selected in game. It makes more sense rather than a mod setting.

**Comment by LOUDO56** [comment]
Ohh okay my bad then, sorry for the bother.

**Pull request merged**
